custom_cms_code/ViewLayer/Controllers/WebsiteController.cs
using DataLayer;
using LogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ViewLayer.Controllers
{
    public class WebsiteController : Controller
    {
        private WebsiteContainer wCont = new WebsiteContainer(new WebsiteDAL());
        private PageContainer pCont = new PageContainer(new PageDAL());
        // GET: WebsiteController
        public ActionResult Index()
        {
            return View(wCont.GetAllWebsites());
        }

        public ActionResult Pages(int id)
        {
            ViewData["CurrentWebsiteName"] = wCont.FindWebsiteById(id).Name;
            ViewData["CurrentWebsiteDomain"] = wCont.FindWebsiteById(id).Domain;
            return View(pCont.GetAll(id));
        }

        // GET: WebsiteController/Details/5
        public ActionResult Details(int id)
        {
            return View(wCont.FindWebsiteById(id));
        }

        // GET: WebsiteController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WebsiteController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                Website newWebsite = new Website(collection["Name"], collection["Domain"]);
                wCont.CreateWebsite(newWebsite);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["Error"] = e;
                return View();
            }
        }

        // GET: WebsiteController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(wCont.FindWebsiteById(id));
        }

        // POST: WebsiteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                Website newWebsite = new Website(Convert.ToInt32(collection["Id"]), collection["Name"], collection["Domain"]);
                wCont.UpdateWebsite(newWebsite);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["Error"] = e;
                return View();
            }
        }

        // GET: WebsiteController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(wCont.FindWebsiteById(id));
        }

        // POST: WebsiteController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                wCont.DeleteWebsite(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                ViewData["Error"] = e;
                return View();
            }
        }
    }
}

custom_cms_code/ViewLayer/Views/Shared/_Layout.cshtml
@{
    ViewData["AppName"] = "Versluis CMS";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["AppName"] - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["AppName"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Website" asp-action="Index">Websites</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="container">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ViewLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>